group: edge
group: deprecated-2017Q1
language: python

python:
  - "2.7"

before_install:
  - "sudo apt-get purge openjdk*"
  - "sudo apt-get purge oracle-java7-*"

addons:
  apt:
    packages:
    - oracle-java8-installer
    - oracle-java8-set-default

env:
  global:
    - JAVA_HOME=/usr/lib/jvm/java-8-oracle

install:
  - travis_wait 20 make install

script:
  - make test

after_success:  
  - make coveralls

#notifications:
#  webhooks: https://galaxy.ansible.com/api/v1/notifications/
notifications:
  slack:
    on_success: always
    on_failure: always
    rooms:
      - buluma:QWpyLHvuvJe5aduZtGs7euUa#general
      - buluma:QWpyLHvuvJe5aduZtGs7euUa#ansible
  email:
    recipients:
      - me@buluma.me.ke
      - michael@buluma.me.ke
    on_success: always # default: change
    on_failure: always # default: always
